name: 'ALM Octane GitHub Actions Integration'
description: 'Sends CI/CD data from GitHub Actions to ALM Octane.'
inputs:
  octaneUrl:
    description: 'Url of ALM Octane instance'
    required: true
  octaneSharedSpace:
    description: 'Shared Space ID'
    required: true
  octaneWorkspace:
    description: 'Workspace ID'
    required: true
  octaneClientId:
    description: "ALM Octane API Access Client ID"
    required: true
  octaneClientSecret:
    description: 'ALM Octane API Access Client Secret'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'