name: CI
on: [workflow_dispatch]


jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'temurin'
        - name: Build and Run Tests
          run: mvn --batch-mode --update-snapshots verify
        - name: JUnit Report Action
          uses: mikepenz/action-junit-report@v3.7.1
            with:
              report_paths: '**/target/*/*test*.xml'


