name: CI
on: [workflow_dispatch]


jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'temurin'
        - run: mvn --batch-mode --update-snapshots verify
        - run: mkdir reports && cp target/*/*test*.xml reports
        - uses: actions/upload-artifact@v3
          with:
            name: Package
            path: reports


